name: Send Mastodon Post

on:
  workflow_call:
    secrets:
      MASTODON_ACCESS_TOKEN:
        required: true
      MASTODON_URL:
        required: true

jobs:
  send_mastodon:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Generate URL and send toot to Mastodon
        id: mastodon
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +"%Y-%m-%d")
          YEAR=$(date +"%Y")
          JAVA_VERSION=$(grep -oP '(?<=java: \[)\d+(?=\])' .github/workflows/rungatling.yml)
          URL="https://ozkanpakdil.github.io/microservicetests/$YEAR/$DATE-microservice-framework-test-$JAVA_VERSION.html"
          echo "URL=$URL" >> $GITHUB_ENV
          # Get the last 3 commit messages
          CHANGELOG=$(git log -3 --pretty=format:"- %s")
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Send toot to Mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} 
          url: ${{ secrets.MASTODON_URL }} 
          message: |
            Latest microservice test framework comparison is released here ${{ env.URL }}
            Changelog:
            ${{ env.CHANGELOG }}